### ISSUE TITLE
关于判定区间和滑条的判定方式

### ISSUE THREAD

**Issue by lamda05** [Mania-Visualization-Project/Mania-Replay-Master#4]
我又来了（

之前我在B站视频的评论区里说滑条尾的判定是正常判定的1.5倍，不过这样时候还是有些滑条的判定结果与实际不符。后来我试着解包了osu!stable研究了一下，得到了一些结论，包括判定区间和OD的关系，以及滑条的判定。具体见：[这↑里↓](https://lamda05.netlify.app/docs/mania_number/acc.html)。

太长不看版：

- Nomod时，从彩300到miss的判定区间分别为16、34+3×(10-OD)、67+3×(10-OD)、97+3×(10-OD)、121+3×(10-OD)、158+3×(10-OD)毫秒；
- EZ和HR时，判定区间分别变为1.4倍和1/1.4；
- 滑条的判定由滑条头的误差和滑条头与滑条尾的误差之和共同决定。

**Comment by Keytoyze** [comment]
您也太吊了（扑通
我暑假研究一下

**Comment by Keytoyze** [comment]
有个困扰我很久的问题在您的雄文里面没有找到答案，这里请教一下大佬：
情况一：假设同一轨道连续两个键A和B，其中键A在**晚于**判定线的200区域，键B在**早于**判定线彩300的区域。这个时候按下键，系统会认为是键A还是键B被判定？
情况二：和上面一样，但是键B在**晚于**判定线彩300的区域，这个时候会怎么判定？
情况三：按键A在**晚于**判定线的50区域，按键B在**晚于**判定线的300区域？
我试验以后发现这个规则及其复杂。如果采用“离判定线最近者先判定”原则，那么结果会出现大量的误击打miss。如果采用“更早者优先判定”的原则，情况一和二都可以正确地判定，但是情况三就不正确了。我目前采用的是后面这个原则，所以在一些极限情况下会出现很多的early miss。
不知道大佬有什么高见？

**Comment by lamda05** [comment]
我个人是把轨道当成堆栈一样的结构来理解的，如果比较早的note不通过按键使其出栈或超出判定区间而自动出栈的话，按键行为是不能作用于之后的note的。

您提到的第三种情况下，A晚于50的判定区间时，其可判定区间已经结束（miss的判定区间是单向的），因此按键将作用于B。

**Comment by lamda05** [comment]
@Keytoyze 我最近又研究了一下，发现之前的结论有些错误之处。[这里](https://lamda05.netlify.app/docs/mania_number/acc.html)的文章已经更新。改变的地方主要包括：

- note之后不仅没有miss判定区间，也没有50判定区间。所以普通note其实在100判定区间结束后就miss了。例如[这个](https://www.bilibili.com/video/BV1Q7411G7W9)和[这个](https://www.bilibili.com/video/BV1vE411c73P)视频中，出现的按键过晚导致的50在游戏中都实际为miss。

- 滑条的判定是以每次按键均单独判定，只有最后一次按键用于结算（具体见上面的文章）。

**Comment by Keytoyze** [comment]
> @Keytoyze 我最近又研究了一下，发现之前的结论有些错误之处。[这里](https://yuanshuai0217.github.io/Gitbook/mania_number/acc.html)的文章已经更新。改变的地方主要包括：
> 
> * note之后不仅没有miss判定区间，也没有50判定区间。所以普通note其实在100判定区间结束后就miss了。例如[这个](https://www.bilibili.com/video/BV1Q7411G7W9)和[这个](https://www.bilibili.com/video/BV1vE411c73P)视频中，出现的按键过晚导致的50在游戏中都实际为miss。
> * 滑条的判定是以每次按键均单独判定，只有最后一次按键用于结算（具体见上面的文章）。

如果这么说的话，那之前的判定顺序也有答案了。之前总是会把某些miss判定为50，结果最终结果往往有所出入。等我考完试以后会再研究一下。

**Comment by Keytoyze** [comment]
@yuanshuai0217 
关于LN判定有几个问题想再对一下。

1. LN部分，所谓“100判定区间”、“50判定区间”指的是不是在原本的判定基础上乘以相应判定倍数，得到的新判定区间？

2. > 若滑条尾的50判定区间结束时，滑条仍处在按下状态，则该滑条的可判定状态仍会结束，以当前时间作为按键结束时间。所以只要滑条头的判定足够准，你甚至可以在滑条按得太过的情况下拿到200判定。

但是，200判定不是需要同时满足按键头+按键尾都在指定区间里面的条件吗？按得太晚的话，岂不是不满足按键头的条件了？

3. >若按键开始时间在滑条头之前的miss判定区间内，则将按键开始时间设置为滑条结束时间−1。

这个1的单位是什么？毫秒，还是秒？

4. 大佬有没有研究过v2下面的LN判定？v2下面，开始和结束是会分开判定的，那么如果一个滑条在可判定状态内被按下多次，那么是不是滑条头用第一个按键判定，滑条尾用最后一个按键判定？判定倍数和v1是否也相同？

5. 大哥是怎么知道这么复杂申必的LN判定规则的呢？能不能把参考文献、参考代码或者探索过程也贴一贴？

**Comment by lamda05** [comment]
@Keytoyze 

1. LN部分的“判定区间”也和其他部分一样是正常的判定区间，只有在滑条尾判定时才是乘以倍数的判定。
2. 因为滑条尾的判定是滑条头的误差和滑条尾的误差之和<2（或2.2、2.4）×判定区间就可以，假如滑条头误差几乎为0，滑条尾按得太过，把50的判定区间视为按键结束时间，此时依然满足小于2×200的判定区间。（可能是我那一段让公式换行导致歧义了，现在已经修改表达方式）
3. 1的单位是毫秒。
4. 现在我也在写ScoreV2部分……不过我也马上要期末考试了，估计会拖得久一点。不过滑条头用第一个按键判定，滑条尾用最后一个按键判定应该也是和V1一样的。

**Comment by Keytoyze** [comment]
@yuanshuai0217 
> 若按键开始时间在滑条头之前的miss判定区间内，则将按键开始时间设置为滑条结束时间−1。

这个对于按键结束时间有没有要求？开始在miss之内，结束也在miss之内难道也算这种情况吗？

> 3. 1的单位是毫秒。

这个建议你在文章里面补充一下。。。

**Comment by lamda05** [comment]
@Keytoyze 
（刚才我理解错误了……）对结尾时间好像没有要求。这的确会导致可能记录的结束时间比开始时间还要早……极短的滑条（例如愚人月中出现的）的判定的确很迷。

单位毫秒已经补充，感谢提醒。

**Comment by Keytoyze** [comment]
@yuanshuai0217 

![LN_judge](https://user-images.githubusercontent.com/32433040/85915168-bffefe80-b877-11ea-9d52-ffdbe466b70a.png)

我按照您的文章补充了个LN的判定规则图，您可以补充到文章里面（看大段文字真的头疼orz）。也帮忙检查一下有没有啥问题

**Comment by lamda05** [comment]
@Keytoyze 感谢补充。当时我写那一段的时候就感觉自己写出来的不像人话【捂脸】

需要指出的几点：

1. 滑条头部后面有50判定区间，这没问题。只有到了滑条头部的50判定区间之后，滑条仍没有被按下的话，才会断combo。（因为这些内容和判定没有关系，就放在连击数那一节去了）但是需要注意普通note后面是没有50判定区间的。
2. 单独看滑条尾部的话，判定区间其实根本不会变宽：决定滑条尾部是否判定时，所用到的50和100判定区间都是正常、未超级（划掉）加倍的判定区间。只是因为滑条尾最终判定时是和滑条头的误差相加之后再计算，所以假设滑条头的误差为0，则滑条尾用于决定判定结果的判定区间会变为原来的2倍，但用于决定滑条尾部是否判定的判定区间依然不变。此时滑条能够得到的判定结果只有彩300、黄300、200、miss，因为200的判定区间的2倍比50的判定区间还要大。而滑条头部的误差变化的话，滑条尾用于决定判定结果的判定区间也会变化。

我计划写一个网页来演示滑条判定，同时可以显示滑条头不同误差时滑条尾部的判定区间。

**Comment by Keytoyze** [comment]
@yuanshuai0217 

> 2. 单独看滑条尾部的话，判定区间其实根本不会变宽：决定滑条尾部是否判定时，所用到的50和100判定区间都是正常、未超级（划掉）加倍的判定区间。只是因为滑条尾最终判定时是和滑条头的误差相加之后再计算，所以假设滑条头的误差为0，则滑条尾用于决定判定结果的判定区间会变为原来的2倍，但用于决定滑条尾部是否判定的判定区间依然不变。此时滑条能够得到的判定结果只有彩300、黄300、200、miss，因为200的判定区间的2倍比50的判定区间还要大。而滑条头部的误差变化的话，滑条尾用于决定判定结果的判定区间也会变化。

这个变宽应该是我为了在一张图里面塞下整个部分，所以把左边拉窄了，只是个视觉效果。不过确实会造成误会，我修改了一下图：
![LN_judge](https://user-images.githubusercontent.com/32433040/85916001-e1171d80-b87e-11ea-9d25-e0cf74a25199.png)

**Comment by lamda05** [comment]
@Keytoyze 这样的话，这张图就没什么问题了。

**Comment by Keytoyze** [comment]
@yuanshuai0217 还有就是我没收到你发过来的源码。如果方便的话，你可以加一下QQ 2242836621。
